<?php
class Cylinder extends Circle{

    public int $height;

    public function __construct($name, float $radius,$height)
    {
        parent::__construct($name, $radius);
        $this->height=$height;
    }

    public function calculateArea(): float
    {
        return parent::calculateArea() * 2 + parent::calculatePerimeter()* $this->height ; // TODO: Change the autogenerated stub
    }

    public function calculateVolume(): float
    {
        return parent::calculateArea() * $this->height;
    }
}